# Generated by Django 5.1.4 on 2025-08-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_excursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=100)),
                ('pupil_count', models.PositiveIntegerField()),
                ('other_people_count', models.PositiveIntegerField()),
                ('excursion_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('transportation', models.CharField(max_length=255)),
                ('probable_length', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.TextField()),
                ('activities', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Excursion',
        ),
    ]
