# Generated by Django 5.1.4 on 2025-08-07 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_excursionregistration_delete_excursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vehicle_plate', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vehicle_capacity', models.PositiveIntegerField(default=0)),
                ('vehicle_color', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('website', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='activities',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='class_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='excursion_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='food',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='other_people_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='probable_length',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='pupil_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='school_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='transportation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
