# Generated by Django 5.1.4 on 2025-08-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_driver_info_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
