# Generated by Django 5.1.4 on 2025-08-09 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0006_hotel_breakfast_included_hotel_caffe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog_photos/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st.user')),
            ],
        ),
    ]
