# Generated by Django 5.1.4 on 2025-08-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reading_time',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='small_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
