# Generated by Django 5.1.4 on 2025-08-10 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0008_blog_reading_time_blog_small_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionregistration',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='excursionregistration',
            name='location',
        ),
        migrations.RemoveField(
            model_name='excursionregistration',
            name='other_people_count',
        ),
        migrations.RemoveField(
            model_name='excursionregistration',
            name='pupil_count',
        ),
        migrations.RemoveField(
            model_name='excursionregistration',
            name='school_name',
        ),
        migrations.AddField(
            model_name='excursionregistration',
            name='accommodation_type',
            field=models.CharField(default='', max_length=100, verbose_name='დარჩენის ტიპი'),
        ),
        migrations.AddField(
            model_name='excursionregistration',
            name='approximate_age',
            field=models.CharField(default='', max_length=100, verbose_name='დაახლოებითი ასაკი'),
        ),
        migrations.AddField(
            model_name='excursionregistration',
            name='destination',
            field=models.CharField(default='', max_length=255, verbose_name='სასურველი მოგზაურობის დასრულების ადგილი'),
        ),
        migrations.AddField(
            model_name='excursionregistration',
            name='excursion_type',
            field=models.CharField(default='', max_length=100, verbose_name='ექსკურსიის ტიპი'),
        ),
        migrations.AddField(
            model_name='excursionregistration',
            name='school',
            field=models.CharField(default='', max_length=255, verbose_name='სახელი გვარი'),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='activities',
            field=models.TextField(default='', verbose_name='დამატებითი აქტივობები'),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='საშუალო ბიუჯეტი'),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='მოგზაურობის დაწყების ადგილი'),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='კომენტარი'),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='excursion_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='სასურველი თარიღი'),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='food',
            field=models.TextField(default='', verbose_name='კვების მოთხოვნები'),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='probable_length',
            field=models.CharField(default='', max_length=100, verbose_name='სავარაუდო ხანგრძლივობა'),
        ),
        migrations.AlterField(
            model_name='excursionregistration',
            name='transportation',
            field=models.CharField(default='', max_length=255, verbose_name='ტრანსპორტირების ტიპი'),
        ),
    ]
